# Generated by Django 5.1.7 on 2025-03-09 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('redirect_url', models.URLField()),
                ('is_private', models.BooleanField(default=False)),
                ('redirect_identifier', models.CharField(db_index=True, editable=False, max_length=10, unique=True)),
            ],
        ),
    ]
