# Generated by Django 5.1.7 on 2025-03-11 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectrule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirect_rules', to='custom_users.customuser'),
        ),
    ]
